# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test of xml build.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  xml_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Xapian
      run: |
        sudo apt-get install -y libxapian30
        sudo apt-get install -y libxapian-dev
    - name: Install dependencies
      working-directory: webapp
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Tests for metadata
      working-directory: webapp/metadata/tests
      run: |
        pytest xml_meta_test.py
        pytest parse_test.py
        pytest metadata_test.py
    - name: Test for log_parser
      working-directory: webapp
      run: |
        pytest log_parser_test.py
